### ISSUE TITLE
TypeError: GObject.__init__() takes exactly 0 arguments (2 given)

### ISSUE THREAD

**Issue by Kracozebr** [ml6team/deepstream-python#10]
Try to run your code on Jetson Xavier and get the error, that can not understand:
```
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    run_pipeline(args.source_uri)
  File "/mnt/ext/deepstream-python/deepstream/app/core.py", line 15, in run_pipeline
    output_format="mp4",
  File "/mnt/ext/deepstream-python/deepstream/app/pipeline.py", line 106, in __init__
    self._create_elements()
  File "/mnt/ext/deepstream-python/deepstream/app/pipeline.py", line 357, in _create_elements
    self.sink_bin = self._create_mp4_sink_bin()
  File "/mnt/ext/deepstream-python/deepstream/app/pipeline.py", line 284, in _create_mp4_sink_bin
    mp4_sink_bin.add_pad(Gst.GhostPad("sink", nvvidconv3.get_static_pad("sink")))
TypeError: GObject.__init__() takes exactly 0 arguments (2 given)
```
It's hard to understand why this error occurs, any suggestions ?

**Comment by Joxis** [comment]
Are you using the provided Dockerfile? It seems to be a version mismatch

**Comment by Kracozebr** [comment]
No. Don't use docker it is provided for x86, not for arm. 
```
FROM nvcr.io/nvidia/deepstream:6.1-devel
```
For now I'm using deepstream 6.0 I've tried to check commits and I saw  that there is small difference in code so I switched to previous commit:
```
git checkout aa576540016f3a02565b2ba09c3d8638836896ee
```

**Comment by Kracozebr** [comment]
I executed 
```
sudo apt install -y python3-gi python3-gst-1.0
```
And the issue disappeared
