### ISSUE TITLE
Get an error when running the sample 

### ISSUE THREAD

**Issue by maoztamir** [ml6team/deepstream-python#8]
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    run_pipeline(args.source_uri)
  File "/home/ubuntu/deepstream-python/deepstream/app/core.py", line 11, in run_pipeline
    pipeline = Pipeline(
  File "/home/ubuntu/deepstream-python/deepstream/app/pipeline.py", line 106, in __init__
    self._create_elements()
  File "/home/ubuntu/deepstream-python/deepstream/app/pipeline.py", line 357, in _create_elements
    self.sink_bin = self._create_mp4_sink_bin()
  File "/home/ubuntu/deepstream-python/deepstream/app/pipeline.py", line 284, in _create_mp4_sink_bin
    mp4_sink_bin.add_pad(Gst.GhostPad("sink", nvvidconv3.get_static_pad("sink")))
TypeError: GObject.__init__() takes exactly 0 arguments (2 given)

**Comment by Joxis** [comment]
Hi @maoztamir 

Did you follow these exact steps described in the README? Did you make any changes to the code?

**Comment by maoztamir** [comment]
No changes, but I am running this directly on a Jetson AGX , not with the docker.

**Comment by Joxis** [comment]
Could you share some extra information such as the dependency versions you are working with? Thanks!

**Comment by Joxis** [comment]
I'm going to close this issue due to inactivity. Feel free to reopen if your issue is still relevant.
